### ISSUE TITLE
Empty `full_command` input causes action to fail even if deploy succeeds

### ISSUE THREAD

**Issue by hartsick** [18F/cg-deploy-action#2]
If `push_arguments` are provided as input rather than `full_command`, the action fails with exit code 2.

Relevant line: https://github.com/18F/cg-deploy-action/blob/42cccc45fa14434fcc01f28572ff19657b48671e/action.yml#L54

Relevant output I saw in the Github Action logs:
```
/home/runner/work/_temp/5346b49e-a068-47b1-8f3d-9094a761b2ee.sh: line 5: syntax error near unexpected token `||'
Error: Process completed with exit code 2.
```

**Comment by rahearn** [comment]
commit that caused ☝🏻 to be fixed: https://github.com/18F/notifications-api/pull/16/commits/6a7e5aa77635dbb6e71d6b04d6f4d9bcfa6b9555
